# Cloudflare Pages 配置文件
name = "iprompt"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:web"

[build.environment]
NODE_VERSION = "18"

[[build.environment.variable]]
key = "VITE_PORT"
value = "13000"

# 静态资源缓存策略
[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "/locales/*"
[headers.values]
"Cache-Control" = "public, max-age=3600"

# 安全头
[[headers]]
for = "/*"
[headers.values]
"X-Content-Type-Options" = "nosniff"
"X-Frame-Options" = "DENY"
"X-XSS-Protection" = "1; mode=block"
"Referrer-Policy" = "strict-origin-when-cross-origin"
"Permissions-Policy" = "geolocation=(), microphone=(), camera=()"