name: Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install
          # Force install platform-specific rollup binary
          npm install @rollup/rollup-linux-x64-gnu
      
      - name: Build Web
        run: npm run build:web
      
      - name: Upload Web build
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist/

  build-tauri:
    name: Build Tauri (${{ matrix.platform.name }})
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: 'macOS-x64'
            os: macos-latest
            target: 'x86_64-apple-darwin'
          - name: 'macOS-arm64' 
            os: macos-latest
            target: 'aarch64-apple-darwin'
          - name: 'Windows'
            os: windows-latest
            target: 'x86_64-pc-windows-msvc'
          - name: 'Linux'
            os: ubuntu-latest
            target: 'x86_64-unknown-linux-gnu'
    
    runs-on: ${{ matrix.platform.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}
      
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      
      - name: Install Linux dependencies
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          # For Ubuntu 24.04, we need to use webkit2gtk-4.1 instead of 4.0
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev librsvg2-dev
      
      - name: Install npm dependencies
        run: |
          npm cache clean --force
          npm install
          # Force install platform-specific rollup binary for each OS
          if [ "${{ matrix.platform.os }}" == "ubuntu-latest" ]; then
            npm install @rollup/rollup-linux-x64-gnu
          elif [ "${{ matrix.platform.os }}" == "macos-latest" ]; then
            npm install @rollup/rollup-darwin-arm64
          elif [ "${{ matrix.platform.os }}" == "windows-latest" ]; then
            npm install @rollup/rollup-win32-x64-msvc
          fi
        shell: bash
      
      - name: Build Tauri
        run: npx tauri build --target ${{ matrix.platform.target }}
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.platform.name }}
          path: |
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.app
            src-tauri/target/release/bundle/**/*.msi  
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.AppImage